### PR TITLE
Remove multi page editor and refactor live config

### LINKED ISSUE #77: Remove multi-page editor
With the removal of the editor page and preset page in favour of global ones, multi-page editor seems to be an overkill with too much emptiness.

### PR DESCRIPTION
**Pull request by tabjy**
Closes #77

### CODE REVIEW

**Comment by tabjy** [comment]
This pull request:
- removes overview page and moves info to config page (mainly global config data)
- removes editor tab in favour of the global one
- removes preset tab in favour of the global preset manager
- restructure packages so they make more sense after the multi-page editor is gone
- refactor config live for better UI design

The pr is complete, however, I'm not sure if I'll have enough time to deal with all the spotbugs problems before I officially leave

**Review by aptmac — APPROVED** [review]
@tabjy Sorry for the delay here. The changes look good to me and this can be merged.

On the topic of spotbugs, most of the errors (4/5) are in the local `spotbugs-exclude.xml` here, but because they aren't patched over in the `jmc/configuration/spotbugs/spotbugs-exclude.xml` they aren't filtered out in the test run. The "new" spotbugs issue is the `RV_RETURN_VALUE_IGNORED_BAD_PRACTICE` on `org.openjdk.jmc.console.ext.agent.editor.AgentEditorUi.refresh()`, but that can be cleaned up in either a future patch or added to the exclude xml.

I have a patch that updates `diff.patch` to append the jmc-agent-plugin `spotbugs-exclude.xml` with the one in jmc, so once this is in I'll make a PR to merge it, if that's okay. I notice there's an issue #51 to ensure that `spotbugs-exclude.xml` is minimum, so that can be accessed once the builds are green again.

**Comment by tabjy** [comment]
Hi @aptmac! Good to hear from you! Sorry I've a bit busy and not seen your comment.

Thank for the diff patch. I'm perfectly okay with it. Let me know if you need any help and/or additional info. Thanks!

**Comment by tabjy** [comment]
Do you want to squash and merge? It looks like I still got permission...

**Comment by aptmac** [comment]
> Do you want to squash and merge? It looks like I still got permission...

Hey! Thanks for the poke, I've gone and merged it

**Pull request merged**
