### PR TITLE
Make event feature table

### LINKED ISSUE #38: Create a table to view events in the Live Config page
Design described in #37

### PR DESCRIPTION
**Pull request by jessyec-s**
Closes #38

### CODE REVIEW

**Review by tabjy — CHANGES_REQUESTED** [review]
Looks awesome overall; however, there are two issues that need to be eventually addressed.

1. In the *Live Config* page, should *Event Tree* be renamed to *Event List* or something else?
2. Since *Live Config* page no longer displays global options (those in `<config>` tag), these options should be displayed somewhere else (*Overview Page* looks good to me). 

The first one is trivial. If you agree we can update it now. The second how, however, I'd open a new issue if needed.

**Comment by jessyec-s** [comment]
> Looks awesome overall; however, there are two issues that need to be eventually addressed.
> 
> 1. In the "Live Config" page, should "Event Tree" be renamed to to "Event List"

I agree with this - ill make the change

> 2. Since "Live Config" page no longer displays global options (those in `<config>` tag), these options should be displayed somewhere else (`Overview Page`) looks good to me.

The information in the config tag is actually there, but its under different elements in the "transformationAttributes" parent element in the table. Perhaps we could modify this to make it more clear?

> 
> The first one is trivial. If you agree we can update it now. The second how, however, I'd open a new issue if needed.

**Comment by tabjy** [comment]
> The information in the config tag is actually there, but its under different elements in the "transformationAttributes" parent element in the table. Perhaps we could modify this to make it more clear?

If I understood correctly, there are global config and per-event config. Both are parameterized by `classprefix:String`, `allowtostring:boolean`, `allowconverter:boolean`. In case a per-event config parameter is missing, the transform registry automatically fills in the value from the global config as the default. 

I believe It's still better to have the *global* config displayed somewhere.

**Review by tabjy — APPROVED** [review]

**Comment by tabjy** [comment]
Anyway, displaying the global config is a different topic. This PR looks good to merge now. Thanks!

**Pull request merged**
