### PR TITLE
Object contributions

### LINKED ISSUE #89: Add Object Contribution to Methods
During the last JMC meeting Marcus highlighted that it would be good to have the agent add an object contribution to methods in the relevant views (i.e. the ability to right click on a method in a view and possibly add instrumentation to it). This would be good to investigate as it would simplify the process of adding probes and remove the need for users to know method descriptors, etc.

### PR DESCRIPTION
**Pull request by Josh-Matsuoka**
Hi,

This PR resolves https://github.com/rh-jmc-team/jmc-agent-plugin/issues/89 adding a menu contribution for IMCFrame and IMCMethod types in JMC. This means you can find e.g. a stack frame inside of mission control and right-click add a method probe for that method. The best way to go about this is to create a preset with a probe defined for that method which the user can then load into a running agent.

### CODE REVIEW

**Comment by aptmac** [comment]
This is cool! The functionality of using the menu-item through to loading the preset looks good to me.

Perhaps not directly in the scope of this PR (but maybe it is ..), the naming of the generated presets could be improved (and maybe a status indicator of some sort would be helpful).

For example, the first time I was giving this a try I wasn't sure if the probes were being created, so I made a handful of them. When I went over to the plugin it was difficult to distinguish between them because they're named "new_preset_#.xml". Likewise I guess using the "Save as a preset..." button in the plugin does naming in a similar way, it would be nice if the name was based off of the probe, or maybe even a user dialog ?

My thoughts are that the preset names generated from the menu contribution could be addressed in this PR, but a follow up issue could be made to address the naming (& renaming?) of presets for the rest of the plugin, what do you think ?

Preset naming (img):
preset-naming

**Comment by Josh-Matsuoka** [comment]
Hey Alex,

That makes sense, a user dialogue is a good idea for naming the preset. we can also make supplying a name optional and have the preset name default to the name of the method used for the probe

**Review by aptmac — APPROVED** [review]
Thanks for adding the dialog, I think this should be okay for completing this issue.

I think there could be follow-up issues for a bit more customization though, mainly having to do with the event naming and id.

For example:
2021-04-15-114419_653x299_scrot

The dialog made it a lot easier to figure out which event preset to apply, but once applied the id & name are still basic. Perhaps now that there's a dialog there could be additional customization controls for ids and names and such ?

**Comment by Josh-Matsuoka** [comment]
Sounds good, as you said I think this is probably better for a follow-up issue. I'll open it after merging this

**Pull request merged**
